# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2020

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/index.html
  About: /about/index.html


# menu
archive_type: 'yearly'
tag_type: 'monthly'
show_count: false

# 是否开启toc
# toc: true
toc:
  list_number: true  # 是否显示数字排序
#Tag 页面的标题
tagTitle: Tags

theme:
  color: Default
  fancybox: false

favicon: /img/favicon.ico

# Miscellaneous
google_analytics:
gauges_analytics:
twitter: azhari_skb
fb_admins: bgkumbang
instagram: bgkumbang
github: bgkumbang
linkedin: bgkumbang

# ===========================================
# Version
# ===========================================
version: 1.1
